spring.application.name=api_monitoring_system


# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/api_monitor_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vedant26}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=${JWT_SECRET:v75JdaB7kjDaKn0fhj8faHna0Kb37lnW}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:vedantshingote07@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:tghkvxbbswrnsypb}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true